services:
  - type: web
    name: horoscope-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python scripts/load_to_sqlite.py"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: DB_PATH
        value: data/horoscope.db
